
import React from 'react';

const Hero: React.FC = () => {
  return (
    <section className="relative min-h-[calc(100vh-80px)] flex items-center overflow-hidden pt-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full py-12 lg:py-0">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-8 animate-fade-in-up">
            <div className="inline-flex items-center px-3 py-1 rounded-full border border-primary/30 bg-primary/10 backdrop-blur-sm">
              <span className="w-2 h-2 rounded-full bg-primary mr-2 animate-pulse"></span>
              <span className="text-xs font-semibold tracking-wider text-primary uppercase">AI-Powered Engine</span>
            </div>
            
            <h1 className="text-5xl lg:text-7xl font-bold leading-[1.1] text-slate-900 dark:text-white">
              AI Career <br/>
              Mapping for <br/>
              <span className="font-script text-secondary transform -rotate-2 inline-block ml-2 relative">
                Teenagers
                <svg className="absolute -bottom-2 left-0 w-full" fill="none" height="10" viewBox="0 0 200 9" xmlns="http://www.w3.org/2000/svg">
                  <path d="M2.00025 6.99997C2.00025 6.99997 101.5 0.999995 198.5 2.5" stroke="#F97316" stroke-linecap="round" stroke-width="3"></path>
                </svg>
              </span>
            </h1>
            
            <p className="text-lg text-slate-600 dark:text-slate-400 max-w-lg leading-relaxed">
              Unlock your potential with personalized career paths generated by advanced AI. Designed specifically for the next generation of innovators, dreamers, and leaders.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 pt-4">
              <a 
                href="#" 
                className="flex items-center justify-center bg-primary hover:bg-teal-400 text-slate-900 text-lg font-bold px-8 py-4 rounded-full btn-glow transition-all"
              >
                Start Career Mapping
              </a>
              <button className="flex items-center justify-center px-8 py-4 rounded-full border border-slate-300 dark:border-white/20 text-slate-700 dark:text-white hover:bg-slate-100 dark:hover:bg-white/10 transition-all group">
                <span className="material-icons-round mr-2 group-hover:text-primary transition-colors">play_circle</span>
                Watch Demo
              </button>
            </div>
          </div>

          <div className="relative lg:h-[600px] flex items-center justify-center">
            {/* Background Glows */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-indigo-500/20 rounded-full blur-3xl filter mix-blend-screen dark:mix-blend-lighten"></div>
            <div className="absolute top-1/2 left-1/2 -translate-x-1/3 -translate-y-1/3 w-[400px] h-[400px] bg-primary/20 rounded-full blur-3xl filter mix-blend-screen dark:mix-blend-lighten"></div>
            
            <div className="relative z-10 w-full max-w-lg mx-auto transform hover:scale-105 transition-transform duration-500">
              <div className="relative w-full aspect-square flex items-center justify-center">
                <img 
                  alt="Teenagers running" 
                  className="object-contain w-full h-full drop-shadow-2xl animate-float" 
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuAXSxFuH-tPNiHg-mxdh972WXtWcpwi435xVYXBJLlwwPz3qOgOEJPXDsb3OfOlNQD6KZFYU3-DR7Yug92huqD20NGl7o-7UNsifeYPdFgfPJ_kFJDHQI9sPyhjPuPXnD9VeZxRiGFsdJeavCWySNC0ANHrwD5-e7e6Fxb-kWdwbJHKu0CqOgRpH6-zSsaMvYDSAP1n8lF425D5qbSAlxh_1NF2PMBVVz688zfT2aj5vFcVs-3JcGJFCDH8d8CoCFeVLtDpMaOjSnh0" 
                />
              </div>
            </div>

            {/* Floating Card */}
            <div className="absolute top-20 right-0 glass-card p-4 rounded-2xl animate-bounce-slow hidden lg:block">
              <div className="flex items-center gap-3">
                <div className="bg-orange-100 dark:bg-orange-500/20 p-2 rounded-lg text-secondary">
                  <span className="material-icons-round text-xl">psychology</span>
                </div>
                <div>
                  <div className="text-xs text-slate-500 dark:text-slate-400 font-medium">Match Score</div>
                  <div className="text-sm font-bold text-slate-800 dark:text-white">98% Fit</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
